# Generated by Django 3.0.1 on 2019-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20191226_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#f44336', 'red'), ('#e91e63', 'pink'), ('#2196f3', 'blue')], max_length=7)),
            ],
        ),
    ]
